package com.romeoDjoman.app_ecommerce_spring.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;

import java.util.Collection;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

@Getter
@RequiredArgsConstructor
public enum PermissionType {
    // ADMIN PERMISSIONS
    ADMIN_CREATE,
    ADMIN_READ,
    ADMIN_UPDATE,
    ADMIN_DELETE,
    ADMIN_VIEW_SUBMITTED_PUBLICATIONS,
    ADMIN_VIEW_PUBLICATION,
    ADMIN_MANAGE_CUSTOMERS,
    ADMIN_CREATE_REVIEWER,
    ADMIN_UPDATE_CONTRIBUTOR_PROFILE,
    ADMIN_DISABLE_CONTRIBUTOR,

    // AUTHOR PERMISSIONS
    AUTHOR_CREATE_PUBLICATION,
    AUTHOR_READ,
    AUTHOR_UPDATE,
    AUTHOR_DELETE,
    AUTHOR_DELETE_REVIEWS,
    AUTHOR_VIEW_SUBMITTED_PUBLICATIONS,
    AUTHOR_VIEW_VALIDATED_PUBLICATIONS,
    AUTHOR_VIEW_SUBMITTED_WITH_RESPONSE,
    AUTHOR_COMMUNICATE_WITH_CONTRIBUTORS,
    AUTHOR_VIEW_UNSUBMITTED_PUBLICATION,
    AUTHOR_VIEW_VALIDATED_PUBLICATION,
    AUTHOR_REVIEW_PUBLICATION,
    AUTHOR_SUBMIT_FOR_REVIEW,
    AUTHOR_SUBMIT_FINAL_PUBLICATION,

    // REVIEWER PERMISSIONS
    REVIEWER_CREATE,
    REVIEWER_READ,
    REVIEWER_UPDATE,
    REVIEWER_DELETE,
    REVIEWER_VIEW_PENDING_CONTRIBUTIONS,

    // USER PERMISSIONS
    USER_CREATE_REVIEWS,
    USER_SEARCH_PUBLICATION_BY_KEYWORD,
    USER_SEARCH_PUBLICATION_BY_FILTER,
    USER_VIEW_LATEST_PUBLICATIONS,
    USER_VIEW_TOP_SELLING_PUBLICATIONS,
    USER_VIEW_TOP_RATED_PUBLICATIONS,
    USER_VIEW_PUBLICATION_DETAILS,
    USER_ADD_PUBLICATION_TO_CART,
    USER_VIEW_CART,
    USER_REMOVE_PUBLICATION_FROM_CART,
    USER_CLEAR_CART,
    USER_PROCESS_PAYMENT,
    USER_MANAGE_PROFILE,
    USER_VIEW_ORDER_HISTORY,
    USER_VIEW_SUBSCRIPTION,
    USER_CANCEL_SUBSCRIPTION,
    USER_RENEW_SUBSCRIPTION,
    USER_VIEW_PUBLICATION,
    USER_VIEW_ORDER_DETAILS;
}